'use client'
import { Sparkles, Zap, ImageIcon } from 'lucide-react'
import { useLanguage } from '@/components/language-provider'
export function Hero() { const { t } = useLanguage(); return <section className="relative overflow-hidden"><div className="mx-auto grid max-w-6xl items-center gap-12 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:py-24"><div className="flex flex-col items-start gap-6"><span className="inline-flex items-center gap-2 rounded-full border border-border bg-secondary px-3 py-1 text-xs font-medium text-secondary-foreground"><Sparkles className="size-3.5 text-primary" />{t('heroBadge')}</span><h1 className="text-balance font-serif text-4xl font-semibold leading-tight tracking-tight sm:text-5xl lg:text-6xl">{t('heroTitle')}</h1><p className="text-pretty text-lg leading-relaxed text-muted-foreground">{t('heroDescription')}</p><div className="flex flex-wrap items-center gap-3"><a href="#studio" className="inline-flex h-11 items-center justify-center rounded-lg bg-primary px-6 text-sm font-medium text-primary-foreground transition-opacity hover:opacity-90">{t('startCreating')}</a><a href="#namunalar" className="inline-flex h-11 items-center justify-center rounded-lg border border-border bg-background px-6 text-sm font-medium text-foreground transition-colors hover:bg-secondary">{t('viewSamples')}</a></div><div className="flex flex-wrap gap-6 pt-2 text-sm text-muted-foreground"><span className="inline-flex items-center gap-2"><Zap className="size-4 text-primary" />{t('readySeconds')}</span><span className="inline-flex items-center gap-2"><ImageIcon className="size-4 text-primary" />{t('highQuality')}</span></div></div><div className="relative"><div className="grid grid-cols-2 gap-3 sm:gap-4">{[
  { file: 'product-box.png', alt: 'Qadoqdagi avtomobil aksessuarlari' },
  { file: 'gear-shifter.png', alt: 'Qora charm avtomobil uzatma dastagi' },
  { file: 'siren.png', alt: 'Avtomobil sirenasi va boshqaruv pulti' },
  { file: 'mercedes-emblem.png', alt: 'Mercedes Motors emblemasi' },
].map(({ file, alt }, i) => <img key={file} src={`/showcase/${file}`} alt={alt} className={`${i % 2 ? 'mt-8 aspect-[3/4]' : 'aspect-[4/5]'} w-full rounded-2xl border border-border/80 object-cover shadow-lg`} />)}</div></div></div></section> }
