'use client'

import { Aperture, ChevronDown, Menu, X } from 'lucide-react'
import { useState } from 'react'
import { useLanguage, type Language } from '@/components/language-provider'

export function SiteHeader() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [languageOpen, setLanguageOpen] = useState(false)
  const { language, setLanguage, t } = useLanguage()
  const navItems = [{ label: t('studio'), href: '#studio' }, { label: t('samples'), href: '#namunalar' }, { label: t('features'), href: '#imkoniyatlar' }, { label: t('pricing'), href: '#narxlar' }]
  const changeLanguage = (next: Language) => { setLanguage(next); setLanguageOpen(false) }
  return <header className="sticky top-0 z-50 border-b border-border/60 bg-background/80 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6"><a href="#" className="flex items-center gap-2" aria-label="SkySolve"><span className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground shadow-sm"><Aperture className="size-5" /></span><span className="font-serif text-xl font-semibold tracking-tight">SkySolve</span></a><nav className="hidden items-center gap-7 md:flex">{navItems.map((item) => <a key={item.href} href={item.href} className="text-sm text-muted-foreground transition-colors hover:text-foreground">{item.label}</a>)}</nav><div className="flex items-center gap-2"><div className="relative"><button type="button" onClick={() => setLanguageOpen(!languageOpen)} className="inline-flex items-center gap-1 rounded-lg px-2.5 py-2 text-xs font-semibold text-muted-foreground hover:bg-secondary hover:text-foreground" aria-expanded={languageOpen} aria-label="Выбрать язык">{language.toUpperCase()} <ChevronDown className="size-3" /></button>{languageOpen && <div className="absolute right-0 top-full mt-1 w-20 rounded-xl border border-border bg-card p-1 shadow-lg"><button type="button" onClick={() => changeLanguage('uz')} className={`block w-full rounded-lg px-3 py-2 text-left text-xs ${language === 'uz' ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-secondary'}`}>UZ</button><button type="button" onClick={() => changeLanguage('ru')} className={`block w-full rounded-lg px-3 py-2 text-left text-xs ${language === 'ru' ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-secondary'}`}>RU</button></div>}</div><a href="#studio" className="hidden h-9 items-center justify-center rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground transition-opacity hover:opacity-90 sm:inline-flex">{t('start')}</a><button type="button" onClick={() => setMenuOpen(!menuOpen)} className="inline-flex size-9 items-center justify-center rounded-lg border border-border md:hidden" aria-label={menuOpen ? 'Close menu' : 'Open menu'}>{menuOpen ? <X className="size-4" /> : <Menu className="size-4" />}</button></div></div>{menuOpen && <nav className="border-t border-border bg-background px-4 py-3 md:hidden">{navItems.map((item) => <a key={item.href} href={item.href} onClick={() => setMenuOpen(false)} className="block rounded-lg px-3 py-2.5 text-sm text-muted-foreground hover:bg-secondary hover:text-foreground">{item.label}</a>)}<a href="#studio" onClick={() => setMenuOpen(false)} className="mt-2 inline-flex w-full items-center justify-center rounded-lg bg-primary py-2.5 text-sm font-medium text-primary-foreground">{t('start')}</a></nav>}</header>
}
