'use client'

import { Aperture, ArrowUpRight, Phone, Send, X } from 'lucide-react'
import { useEffect, useState } from 'react'

export function SiteFooter() {
  const [isContactOpen, setIsContactOpen] = useState(false)

  useEffect(() => {
    if (!isContactOpen) return
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') setIsContactOpen(false)
    }
    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [isContactOpen])

  return <>
    <footer className="border-t border-border bg-card/40"><div className="mx-auto grid max-w-6xl gap-10 px-4 py-12 sm:px-6 md:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><div className="flex items-center gap-2"><span className="flex size-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Aperture className="size-4" /></span><span className="font-serif text-lg font-semibold">SkySolve</span></div><p className="mt-4 max-w-xs text-sm leading-relaxed text-muted-foreground">Uzum sotuvchilari uchun mahsulot rasmini, opisaniyasini va kreativini bir joyda tayyorlang.</p></div><div><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-foreground">Mahsulot</p><div className="flex flex-col gap-2 text-sm text-muted-foreground"><a href="#studio" className="hover:text-foreground">Studio</a><a href="#namunalar" className="hover:text-foreground">Namunalar</a><a href="#narxlar" className="hover:text-foreground">Narxlar</a></div></div><div><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-foreground">Yordam</p><div className="flex flex-col gap-2 text-sm text-muted-foreground"><a href="#imkoniyatlar" className="hover:text-foreground">Imkoniyatlar</a><a href="#studio" className="hover:text-foreground">Qanday ishlaydi?</a><button type="button" onClick={() => setIsContactOpen(true)} className="inline-flex items-center gap-1 text-left text-muted-foreground transition-colors hover:text-foreground">Bog‘lanish <ArrowUpRight className="size-3" /></button></div></div><div><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-foreground">SkySolve</p><p className="text-sm leading-relaxed text-muted-foreground">Mahsulotingiz haqida ko‘proq gapiring. Biz esa uni chiroyli ko‘rsatamiz.</p></div></div><div className="border-t border-border"><div className="mx-auto flex max-w-6xl flex-col gap-2 px-4 py-5 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between sm:px-6"><span>© {new Date().getFullYear()} SkySolve. Barcha huquqlar himoyalangan.</span><span>AI yordamchi · Uzum uchun yaratilgan</span></div></div></footer>
    {isContactOpen && <div role="presentation" className="fixed inset-0 z-50 flex items-center justify-center bg-background/75 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) setIsContactOpen(false) }}><div role="dialog" aria-modal="true" aria-labelledby="contact-modal-title" className="w-full max-w-sm rounded-2xl border border-primary/25 bg-card p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Yordam</p><h2 id="contact-modal-title" className="mt-1 font-serif text-2xl font-semibold">Biz bilan bog‘laning</h2></div><button type="button" aria-label="Modalni yopish" onClick={() => setIsContactOpen(false)} className="rounded-lg p-2 text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"><X className="size-4" /></button></div><div className="mt-6 flex flex-col gap-3"><a href="tel:+998916941449" className="flex items-center gap-3 rounded-xl border border-border bg-background px-4 py-3 transition-colors hover:border-primary/50 hover:bg-primary/5"><span className="flex size-9 items-center justify-center rounded-lg bg-primary/15 text-primary"><Phone className="size-4" /></span><span><span className="block text-xs text-muted-foreground">Telefon raqami</span><span className="font-medium">+998 91 694 14 49</span></span></a><a href="https://t.me/a073bb" target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl border border-border bg-background px-4 py-3 transition-colors hover:border-primary/50 hover:bg-primary/5"><span className="flex size-9 items-center justify-center rounded-lg bg-primary/15 text-primary"><Send className="size-4" /></span><span><span className="block text-xs text-muted-foreground">Telegram</span><span className="font-medium">@a073bb</span></span><ArrowUpRight className="ml-auto size-4 text-muted-foreground" /></a></div></div></div>}
  </>
}
